max_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"
wrap_comments = false
normalize_comments = false
empty_item_single_line = true
fn_single_line = false
where_single_line = false
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = false
space_before_colon = false
space_after_colon = true
spaces_within_parens_and_brackets = false
remove_blank_lines_at_start_or_end_of_block = true
fn_args_density = "Tall"
brace_style = "SameLineWhere"
trailing_comma = "Vertical"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
force_explicit_abi = true
write_mode = "Overwrite"
disable_all_formatting = false
skip_children = false
report_todo = "Never"
report_fixme = "Never"
