sudo: required

services:
  - docker

os:
  - linux
  - osx

language: rust

rust:
  - stable

cache:
  - cargo
  - $HOME/docker

addons:
  apt:
    packages:
      - libgettextpo-dev
      - libgpgme11-dev
      - libgpg-error-dev

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install gpgme gettext
      brew link --force gettext
    fi

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

script:
  - cargo doc
  - cargo test --all
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        make lint-scripts
        make stateful-journey-tests
        if [[ -n "$TRAVIS_TAG" ]]; then
          make docs
        fi
    else
        make stateless-journey-tests
    fi

deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: doc/book
    github-token: "$GITHUB_TOKEN"
    on:
      repo: Byron/share-secrets-safely
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME != "osx"
      
env:
  global:
    secure: lsyZVCwegdhKqBxuC/wlWcy9Z1a6u3j+1l6KB9Ayi7xEoV0uLoCnLe3hy4nu6cyS3QLzyzbxjL0eZbH1c+NxiO43rnj3U1anaXNba6+SYHcRV+BUZo/869b/4l0vajT+9NkU61Qw/+8wcplrF4MxeNtIub5GpFSlMNdxJDlnjKBNs6BPYtVje/JMp6U5PCq/qtubsQMoQBRuM/OOdLglPWwRqMYi2KMzytxypQRbHYyT5rri/DydsWT8dM90fUb3PLe/uTZmimZsVF+E3y22Rrasdm83/BE5pMVn65C6spU4GL3RA6qWcTLK95e2ifq+RQ4xj3kDeoyyD8xYrMf5/XuyTJqyZld2xyTQCub9vEw4FpgFeWN0fVdch1YDN7BIAyaCDCO2Mi+dprZmd1sNlyrLe29XK1SylTJqI+dL0Z+wOUIxUSj09Vj7UGSQ/XO3gEFiqHrrTNP5g4DslbUo33Gv1Vq1T8/2G+kd/bK/rmrdAAaOjWRGz3/rQIIUBMLSdBGp/9g5PIDT4SjSWov4hTxsT5fTi+nBHV6narjDi2n2uy8jhz133U7f8xeti8Hg1LjePRRZ8ZJ33khO30/YrYeOOvFqUR3/6S1SllsFpaloykZcYT7UgA5hlQsGxSffPm5BI3hj77SFk1JZ1CH5b/AnM2qRTwnMbPMKfrrXGxg=
