sudo: required

services:
  - docker

os:
  - linux
  - osx

language: rust

rust:
  - stable

cache:
  - cargo
  - $HOME/docker

addons:
  apt:
    packages:
      - libgettextpo-dev
      - libgpgme11-dev
      - libgpg-error-dev

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install gpgme gettext
      brew link --force gettext
    fi

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

script:
  - cargo doc
  - cargo test --all
  # JourneyTests need docker, so it's OK to run them just on one OS. We also just need them once, as journey tests just use the MUSL binary
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        make lint-scripts
        make stateful-journey-tests
    else
        make stateless-journey-tests
    fi
