sudo: required

services:
  - docker

os:
- linux
- osx

language: rust

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

script:
- cargo doc
- cargo test
# JourneyTests need docker, so it's OK to run them just on one OS. We also just need them once, as journey tests just use the MUSL binary
- if [[ "$TRAVIS_OS_NAME" != "osx" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then make journey-tests; fi
