[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
name = "s3-cli"
version = "0.1.0"

description = "The 'share-secrets-safely' CLI to interact with GPG/pass-like vaults."
license = "LGPL-2.1"
repository = "https://github.com/Byron/share-secrets-safely"
homepage = "https://github.com/Byron/share-secrets-safely"
documentation = "https://docs.rs/s3-cli"

[badges]
travis-ci = { repository = "Byron/share-secrets-safely" }

[[bin]]
name = "s3"
path = "src/main.rs"

[dependencies]
clap = "~2.29.0"
failure = "~0.1.1"
s3-vault = {path = "lib/vault", version = "~0.1.0"}
s3-extract = {path = "lib/extract", version = "~0.1.0"}
s3-types = {path = "lib/types", version = "~0.1.0"}
conv = "0.3.3"
lazy_static = "1.0.0"

[workspace]
