[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
name = "s3-cli"
version = "0.1.0"

[[bin]]
name = "s3"
path = "src/main.rs"

[dependencies]
clap = "~2.29.0"
failure = "0.1.1"
s3-vault = {path = "lib/vault"}
s3-extract = {path = "lib/extract"}
s3-types = {path = "lib/types"}



[workspace]
