[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
name = "s3-cli"
version = "0.1.0"

[[bin]]
name = "s3"
path = "src/main.rs"

[dependencies]
clap = "~2.29.0"
failure = "0.1.1"

[workspace]
